// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emiyxuareujqneuyewzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtaXl4dWFyZXVqcW5ldXlld3pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDQxOTIsImV4cCI6MjA2MjYyMDE5Mn0.3u9fmngkh9AsQeRaWpcfs3QBnEZVgTCusjd8L-scI04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);